### ISSUE TITLE
database field for image URL

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-api#24]
@jtorreggiani @iliadeleon

In the models.py file (https://github.com/data-umbrella/event-board-api/blob/main/events/models.py), where can we find a field for "image_url"?

Example of image: 
https://2022.pycon.co/img/tickets/background-intro-tickets-regular.png

cc: @symeneses

**Comment by jtorreggiani** [comment]
@reshamas, I opened a pull request adding the image upload functionality which I'm working on this weekend. I will attach the pull request to this issue.
