### ISSUE TITLE
Weekly Digest Api Endpoints

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-api#59]
## Details
We need to create a subscription and unsubscribe endpoint for the weekly digest.
The UI will be in react via the event board web repository.
The backend is in Django.

## Nice to haves
Ideally, tests should be included for subscribe and unsubscribe.

**Comment by jackwkinsey** [comment]
@dashcraft @jtorreggiani 

Is there some database work that needs to be done around these endpoints as well? Or is that already setup and I'm just not seeing it?

I assume we need a table of emails with a subscription flag? People can sign up for emails with a form and that sends a request to the API with their email, storing it with the flag set to true. 

Then if they decide to unsubscribe via the link in the email, the link would take them to a page to unsubscribe. Confirming that, the call to the API would effectively either set the subscribe flag to false or delete the record altogether?

**Comment by dashcraft** [comment]
We need an intermediate table that contains only emails for users who aren't logged in, unless we want them to be available for all users. I'll check in the morning @jackwkinsey
